/*
Copyright © 2026 Sol

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package merit

import (
	"fmt"
	"github.com/ajstarks/gensvg"
	"github.com/mieuxvoter/majority-judgment-library-go/judgment"
	"image/color"
	"strings"
)

// renderOptions uses the functional options design pattern.
// See https://uptrace.dev/blog/golang-functional-options
type renderOptions struct {
	width                  float64
	height                 float64
	padding                float64
	horizontalSpacing      float64
	verticalSpacing        float64
	gradeCornerRadius      float64
	bgCornerRadius         float64
	bgColor                color.Color
	medianLineColor        color.Color
	medianLineOutlineColor color.Color
	textColor              color.Color
	textOutlineColor       color.Color
	patternColor           color.Color
	gradesPalette          color.Palette
	patterns               []PatternDefinition
}

type RenderOptions func(options *renderOptions)

func WithWidth(width float64) RenderOptions {
	return func(options *renderOptions) {
		options.width = width
	}
}

func WithHeight(height float64) RenderOptions {
	return func(options *renderOptions) {
		options.height = height
	}
}

func WithPadding(padding float64) RenderOptions {
	return func(options *renderOptions) {
		options.padding = padding
	}
}

func WithHorizontalSpacing(horizontalSpacing float64) RenderOptions {
	return func(options *renderOptions) {
		options.horizontalSpacing = horizontalSpacing
	}
}

func WithVerticalSpacing(verticalSpacing float64) RenderOptions {
	return func(options *renderOptions) {
		options.verticalSpacing = verticalSpacing
	}
}

func WithBgColor(bgColor color.Color) RenderOptions {
	return func(options *renderOptions) {
		options.bgColor = bgColor
	}
}

func WithMedianLineColor(medianLineColor color.Color) RenderOptions {
	return func(options *renderOptions) {
		options.medianLineColor = medianLineColor
	}
}

func WithMedianLineOutlineColor(medianLineOutlineColor color.Color) RenderOptions {
	return func(options *renderOptions) {
		options.medianLineOutlineColor = medianLineOutlineColor
	}
}

func WithTextColor(textColor color.Color) RenderOptions {
	return func(options *renderOptions) {
		options.textColor = textColor
	}
}

func WithTextOutlineColor(textOutlineColor color.Color) RenderOptions {
	return func(options *renderOptions) {
		options.textOutlineColor = textOutlineColor
	}
}

func WithPatternColor(patternColor color.Color) RenderOptions {
	return func(options *renderOptions) {
		options.patternColor = patternColor
	}
}

func WithGradesPalette(gradesPalette color.Palette) RenderOptions {
	return func(options *renderOptions) {
		options.gradesPalette = gradesPalette
	}
}

func WithPatterns(patterns []PatternDefinition) RenderOptions {
	return func(options *renderOptions) {
		options.patterns = patterns
	}
}

// const mvBlue = color.NRGBA{R: 36, G: 0, B: 253, A: 255}
const vanity = "<!-- Generated by gensvg -->\n"
const xmlHeader = `<?xml version="1.0"?>`

func RenderLinearProfileSVG(
	proposals []Proposal,
	options ...RenderOptions,
) (string, error) {

	amountOfProposals := float64(len(proposals))

	if amountOfProposals == 0 {
		return "", fmt.Errorf("provide at least one proposal")
	}

	amountOfGrades := len(proposals[0].Tally)
	amountOfJudges := float64(0)
	for _, gradeTally := range proposals[0].Tally {
		amountOfJudges += float64(gradeTally)
	}

	// TBD: check consistency and balance of tallies?  (or just wing it?)

	cfg := renderOptions{
		width:                  512.0,
		height:                 -1.0, // dynamically computed if not set
		padding:                16.0,
		verticalSpacing:        16.0,
		horizontalSpacing:      4.0,
		gradeCornerRadius:      6.0,
		bgCornerRadius:         12.0,
		bgColor:                color.NRGBA{R: 255, G: 255, B: 255, A: 255},
		medianLineColor:        color.NRGBA{R: 1, G: 1, B: 1, A: 255},
		medianLineOutlineColor: color.NRGBA{R: 255, G: 255, B: 255, A: 200},
		textColor:              color.NRGBA{R: 0, G: 0, B: 0, A: 255},
		textOutlineColor:       color.NRGBA{R: 255, G: 255, B: 255, A: 255},
		patternColor:           color.NRGBA{R: 0, G: 0, B: 0, A: 97},
		gradesPalette:          judgment.CreateDefaultPalette(amountOfGrades),
		patterns:               CreateDefaultPatterns(amountOfGrades),
	}
	for _, option := range options {
		option(&cfg)
	}

	// Compute a sensible, dynamic default height
	sensibleDefaultGradeHeight := 48.0
	totalVerticalSpacing := cfg.verticalSpacing * (amountOfProposals - 1)
	if cfg.height == -1.0 {
		cfg.height = amountOfProposals*sensibleDefaultGradeHeight + totalVerticalSpacing
	}

	// Check the consistency of the grades palette
	// TBD: perhaps we could be lenient and loop them around with some modulo instead?
	if len(cfg.gradesPalette) < amountOfGrades {
		return "", fmt.Errorf("grades palette is too small")
	}

	width := cfg.width
	height := cfg.height

	// All's well, let's start generating the SVG
	stringBuilder := new(strings.Builder)
	canvas := gensvg.New(stringBuilder)

	floatPrecision := canvas.Decimals
	canvas.Start(
		width, height,
		// Use a crafty viewBox on the whole svg to enforce our padding
		fmt.Sprintf(
			`viewBox="%.*f %.*f %.*f %.*f"`,
			floatPrecision, -cfg.padding,
			floatPrecision, -cfg.padding,
			floatPrecision, width+2*cfg.padding,
			floatPrecision, height+2*cfg.padding,
		),
	)

	// SVG Definitions
	canvas.Def()

	// We use clipping paths, since overflow does not work properly
	for proposalIndex := range proposals {
		localHeight := (height - totalVerticalSpacing) / (amountOfProposals)
		localY := float64(proposalIndex) * (localHeight + cfg.verticalSpacing)
		canvas.ClipPath(
			fmt.Sprintf(`id="clipProposal%d"`, proposalIndex),
		)
		canvas.Rect(0, localY, width, localHeight)
		canvas.ClipEnd()
	}

	// Background patterns (accessibility — color-impaired)
	amountOfPatterns := len(cfg.patterns)
	patternIds := make([]string, amountOfPatterns)
	for i, patternDefinition := range cfg.patterns {
		patternIds[i] = patternDefinition(canvas, cfg.patternColor)
	}

	// A blurry outline filter for our median vertical line
	canvas.Filter(
		`merit_filter_blurry_outline`,
		// Keyword objectBoundingBox should not be used when the geometry of the applicable element
		// has no width or no height, such as the case of a horizontal or vertical line,
		// even when the line has actual thickness when viewed due to having a non-zero stroke width,
		// since stroke width is ignored for bounding box calculations.
		// When the geometry of the applicable element has no width or height and objectBoundingBox is specified,
		// then the given effect (e.g., a gradient or a filter) will be ignored.
		// Yet we want to apply this filter on such a vertical line — hence, the usage of userSpaceOnUse here.
		`filterUnits="userSpaceOnUse"`,
	)
	for dx := -1; dx <= 1; dx += 2 {
		for dy := -1; dy <= 1; dy += 2 {
			// Note: feDropShadow is not supported natively by the gensvg lib.  (and MRs are ignored there)
			filter := fmt.Sprintf(
				`<feDropShadow dx="%d" dy="%d" stdDeviation="1" flood-color="%s" flood-opacity="%s" />`,
				dx, dy,
				toHex(cfg.medianLineOutlineColor), toOpacity(cfg.medianLineOutlineColor),
			)
			_, _ = canvas.Writer.Write([]byte(filter + "\n"))
		}
	}
	canvas.Fend()

	canvas.DefEnd()

	// Background
	canvas.Roundrect(
		-cfg.padding, -cfg.padding,
		width+2*cfg.padding, height+2*cfg.padding,
		cfg.bgCornerRadius, cfg.bgCornerRadius,
		toFillAttrs(cfg.bgColor),
	)

	//canvas.Rect(0, 0, width, height, "fill:darkred")

	localHeight := (height - totalVerticalSpacing) / (amountOfProposals)
	for proposalIndex, proposal := range proposals {
		localY := float64(proposalIndex) * (localHeight + cfg.verticalSpacing)

		//canvas.Rect(0, localY, width, localHeight, "fill:magenta")

		// Draw the colored rectangles of the grades.
		localX := float64(0)
		for gradeIndex, gradeTally := range proposal.Tally {
			if gradeTally <= 0 {
				continue
			}

			gradeColor := cfg.gradesPalette[gradeIndex]
			gradeWidth := width * float64(gradeTally) / amountOfJudges

			firstGrade := localX == 0
			lastGrade := localX+gradeWidth == width

			rectX := localX
			if !firstGrade {
				rectX += cfg.horizontalSpacing * 0.5
			}
			rectY := localY
			rectW := gradeWidth
			if !firstGrade {
				rectW -= cfg.horizontalSpacing * 0.5
			}
			if !lastGrade {
				rectW -= cfg.horizontalSpacing * 0.5
			}
			rectH := localHeight

			// Grade color
			canvas.Roundrect(
				rectX, rectY,
				rectW, rectH,
				cfg.gradeCornerRadius, cfg.gradeCornerRadius,
				toFillAttrs(gradeColor),
			)
			// Grade pattern
			if amountOfPatterns > 0 {
				patternId := patternIds[gradeIndex%amountOfPatterns]
				canvas.Roundrect(
					rectX, rectY,
					rectW, rectH,
					cfg.gradeCornerRadius, cfg.gradeCornerRadius,
					fmt.Sprintf(`fill="url(#%s)"`, patternId),
				)
			}

			localX += gradeWidth
		}

		// Draw the median vertical line
		canvas.Line(
			width*0.5, localY,
			width*0.5, localY+localHeight,
			fmt.Sprintf(`stroke="%s"`, toHex(cfg.medianLineColor)),
			`stroke-width="4"`,
			`stroke-dasharray="6.472 4"`,
			`filter="url(#merit_filter_blurry_outline)"`,
		)

		// Draw the name of the proposal, and its outline
		nameX := 16.00 // small padding-left
		nameY := localY + 0.5*localHeight
		nameClipper := fmt.Sprintf("clipProposal%d", proposalIndex)
		canvas.Text(
			nameX, nameY,
			proposal.Name,
			fmt.Sprintf(
				`stroke:%s; fill:%s; clip-path: url(#%s)`,
				toHex(cfg.textOutlineColor),
				toHex(cfg.textOutlineColor),
				nameClipper,
			),
			`stroke-width="5"`,
			`font-size="1.3em"`,
			`dominant-baseline="middle"`,
		)
		canvas.Textspan(
			nameX, nameY,
			proposal.Name,
			fmt.Sprintf(
				`stroke:%s; clip-path: url(#%s)`,
				toHex(cfg.textColor),
				nameClipper,
			),
			`font-size="1.3em"`,
			`dominant-baseline="middle"`,
		)
		canvas.Title(proposal.Name)
		canvas.TextEnd()
	}

	canvas.End()

	svg := stringBuilder.String()
	svg = strings.Replace(svg, vanity, "", 1)
	// TBD: perhaps we do not need to specify the encoding
	svg = strings.Replace(svg, xmlHeader, `<?xml version="1.0" encoding="UTF-8"?>`, 1)

	return svg, nil
}
