// SPDX-License-Identifier: MIT

package merit

import (
	"fmt"
	"github.com/ajstarks/gensvg"
	"github.com/mieuxvoter/majority-judgment-library-go/judgment"
	"image/color"
	"math"
	"strings"
)

// renderOptions are set to sane, non-zero defaults when undefined.
type renderOptions struct {
	width                  float64
	height                 float64
	padding                float64
	horizontalSpacing      float64
	verticalSpacing        float64
	gradeHeight            float64 // used only if height is unspecified
	gradeCornerRadius      float64
	bgCornerRadius         float64
	bgColor                color.Color
	medianLineColor        color.Color
	medianLineOutlineColor color.Color
	textColor              color.Color
	textOutlineColor       color.Color
	textShadowColor        color.Color
	patternColor           color.Color
	gradesPalette          color.Palette
	patterns               []PatternDefinition
	fontFamily             string
	proposalFontSize       string
	tallyFontSize          string
}

// RenderOptions uses the functional options design pattern.
// See https://uptrace.dev/blog/golang-functional-options
type RenderOptions func(options *renderOptions)

func WithWidth(width float64) RenderOptions {
	return func(options *renderOptions) {
		options.width = width
	}
}

func WithHeight(height float64) RenderOptions {
	return func(options *renderOptions) {
		options.height = height
	}
}

func WithPadding(padding float64) RenderOptions {
	return func(options *renderOptions) {
		options.padding = padding
	}
}

func WithHorizontalSpacing(horizontalSpacing float64) RenderOptions {
	return func(options *renderOptions) {
		options.horizontalSpacing = horizontalSpacing
	}
}

func WithVerticalSpacing(verticalSpacing float64) RenderOptions {
	return func(options *renderOptions) {
		options.verticalSpacing = verticalSpacing
	}
}

func WithGradeHeight(height float64) RenderOptions {
	return func(options *renderOptions) {
		options.gradeHeight = height
	}
}

func WithGradeCornerRadius(radius float64) RenderOptions {
	return func(options *renderOptions) {
		options.gradeCornerRadius = radius
	}
}

func WithBgCornerRadius(radius float64) RenderOptions {
	return func(options *renderOptions) {
		options.bgCornerRadius = radius
	}
}

func WithBgColor(bgColor color.Color) RenderOptions {
	return func(options *renderOptions) {
		options.bgColor = bgColor
	}
}

func WithMedianLineColor(medianLineColor color.Color) RenderOptions {
	return func(options *renderOptions) {
		options.medianLineColor = medianLineColor
	}
}

func WithMedianLineOutlineColor(medianLineOutlineColor color.Color) RenderOptions {
	return func(options *renderOptions) {
		options.medianLineOutlineColor = medianLineOutlineColor
	}
}

func WithTextColor(textColor color.Color) RenderOptions {
	return func(options *renderOptions) {
		options.textColor = textColor
	}
}

func WithTextOutlineColor(textOutlineColor color.Color) RenderOptions {
	return func(options *renderOptions) {
		options.textOutlineColor = textOutlineColor
	}
}

func WithTextShadowColor(textShadowColor color.Color) RenderOptions {
	return func(options *renderOptions) {
		options.textShadowColor = textShadowColor
	}
}

func WithPatternColor(patternColor color.Color) RenderOptions {
	return func(options *renderOptions) {
		options.patternColor = patternColor
	}
}

func WithGradesPalette(gradesPalette color.Palette) RenderOptions {
	return func(options *renderOptions) {
		options.gradesPalette = gradesPalette
	}
}

func WithPatterns(patterns []PatternDefinition) RenderOptions {
	return func(options *renderOptions) {
		options.patterns = patterns
	}
}

func WithFontFamily(fontFamily string) RenderOptions {
	return func(options *renderOptions) {
		options.fontFamily = fontFamily
	}
}

func WithProposalFontSize(fontSize string) RenderOptions {
	return func(options *renderOptions) {
		options.proposalFontSize = fontSize
	}
}

func WithTallyFontSize(fontSize string) RenderOptions {
	return func(options *renderOptions) {
		options.tallyFontSize = fontSize
	}
}

const vanity = "<!-- Generated by gensvg -->\n"

func RenderLinearProfileSVG(
	proposals []Proposal,
	options ...RenderOptions,
) (string, error) {

	amountOfProposals := float64(len(proposals))

	if amountOfProposals == 0 {
		return "", fmt.Errorf("at least one proposal is required")
	}

	amountOfGrades := len(proposals[0].Tally)
	amountOfJudges := float64(0)
	for _, gradeTally := range proposals[0].Tally {
		amountOfJudges += float64(gradeTally)
	}

	// TBD: check consistency and balance of tallies?  (or just wing it?)

	cfg := renderOptions{
		width:                  512.0,
		height:                 -1.0, // dynamically computed if -1
		padding:                16.0,
		verticalSpacing:        16.0,
		horizontalSpacing:      4.0,
		gradeHeight:            48.0, // a multiple of 16 looks best with patterns
		gradeCornerRadius:      6.0,
		bgCornerRadius:         12.0,
		bgColor:                color.NRGBA{R: 255, G: 255, B: 255, A: 255},
		medianLineColor:        color.NRGBA{R: 1, G: 1, B: 1, A: 255},
		medianLineOutlineColor: color.NRGBA{R: 255, G: 255, B: 255, A: 200},
		textColor:              color.NRGBA{R: 0, G: 0, B: 0, A: 255},
		textOutlineColor:       color.NRGBA{R: 255, G: 255, B: 255, A: 255},
		textShadowColor:        color.NRGBA{R: 0, G: 0, B: 0, A: 255},
		patternColor:           color.NRGBA{R: 0, G: 0, B: 0, A: 97},
		gradesPalette:          judgment.CreateDefaultPalette(amountOfGrades),
		patterns:               CreateDefaultPatterns(amountOfGrades),
		fontFamily:             "Noto Sans, Arial, Helvetica, sans-serif", // OpenDyslexic Nerd Font?
		proposalFontSize:       "1.618em",
		tallyFontSize:          "0.88em",
	}
	for _, option := range options {
		option(&cfg)
	}

	// Compute a sensible, dynamic default height
	totalVerticalSpacing := cfg.verticalSpacing * (amountOfProposals - 1)
	if cfg.height == -1.0 {
		cfg.height = amountOfProposals*cfg.gradeHeight + totalVerticalSpacing
	}

	// Check the consistency of the grades palette
	// TBD: perhaps we could be lenient and loop them around with some modulo instead?
	if len(cfg.gradesPalette) < amountOfGrades {
		return "", fmt.Errorf("grades palette is too small")
	}

	// Compute the internal dimensions of our SVG (without padding)
	doublePadding := 2 * cfg.padding
	height := cfg.height
	width := (cfg.width/cfg.height)*(height+doublePadding) - doublePadding // keep ratio

	// All's well, let's start generating the SVG
	stringBuilder := new(strings.Builder)
	canvas := gensvg.New(stringBuilder)

	floatPrecision := canvas.Decimals
	canvas.Start(
		cfg.width, cfg.height,
		// Use a crafty viewBox on the whole svg to enforce our configurable padding
		fmt.Sprintf(
			`viewBox="%.*f %.*f %.*f %.*f"`,
			floatPrecision, -cfg.padding,
			floatPrecision, -cfg.padding,
			floatPrecision, width+doublePadding,
			floatPrecision, height+doublePadding,
		),
	)

	// SVG Definitions
	canvas.Def()

	// We use clipping paths, since overflow does not work properly
	for proposalIndex := range proposals {
		localHeight := (height - totalVerticalSpacing) / (amountOfProposals)
		localY := float64(proposalIndex) * (localHeight + cfg.verticalSpacing)
		canvas.ClipPath(
			fmt.Sprintf(`id="clipProposal%d"`, proposalIndex),
		)
		canvas.Rect(0, localY, width, localHeight)
		canvas.ClipEnd()
	}

	// Background patterns (accessibility — color-impaired)
	amountOfPatterns := len(cfg.patterns)
	patternIds := make([]string, amountOfPatterns)
	for i, patternDefinition := range cfg.patterns {
		patternIds[i] = patternDefinition(canvas, cfg.patternColor)
	}

	// Using the obvious way to make outlines (a background text with a large stroke) yields ugly artifacts.
	// Therefore, we're using this complex filter instead ; it works wonders, although it's a bit expensive.
	// And since we're invoking creatures from the Dungeon dimension, we've added a shadow for good measure.
	canvas.Filter(
		`merit_filter_clean_outline`,
	)
	canvas.FeMorphology(
		gensvg.Filterspec{In: "SourceAlpha", Result: "DILATED"},
		"dilate",
		2, 2,
	)
	_, _, _, textOutlineAlpha := cfg.textOutlineColor.RGBA()
	canvas.FeFlood(
		gensvg.Filterspec{Result: "COLOR"},
		toHex(cfg.textOutlineColor),
		float64(textOutlineAlpha)/0xffff,
	)
	canvas.FeComposite(
		gensvg.Filterspec{In: "COLOR", In2: "DILATED", Result: "OUTLINE"},
		"in", 0, 0, 0, 0,
	)
	// Note: feDropShadow is not supported natively by the gensvg lib.  (and MRs appear ignored there)
	shadowFilter := fmt.Sprintf(
		`<feDropShadow in="OUTLINE" result="SHADOWED_OUTLINE" dx="%f" dy="%f" stdDeviation="0.5" flood-color="%s" flood-opacity="%s" />`,
		0.618, 1.0, toHex(cfg.textShadowColor), toOpacity(cfg.textShadowColor),
	)
	_, _ = canvas.Writer.Write([]byte(shadowFilter + "\n"))
	canvas.FeMerge(
		[]string{"SHADOWED_OUTLINE", "SourceGraphic"},
	)
	canvas.Fend()

	// Blurry outline filter for our median vertical line
	canvas.Filter(
		`merit_filter_blurry_outline`,
		// > Keyword objectBoundingBox should not be used when the geometry of the applicable element
		// > has no width or no height, such as the case of a horizontal or vertical line,
		// > even when the line has actual thickness when viewed due to having a non-zero stroke width,
		// > since stroke width is ignored for bounding box calculations.
		// > When the geometry of the applicable element has no width or height and objectBoundingBox is specified,
		// > then the given effect (e.g., a gradient or a filter) will be ignored.
		// Yet we want to apply this filter on such a vertical line — hence, the usage of userSpaceOnUse here.
		`filterUnits="userSpaceOnUse"`,
	)
	for dx := -1; dx <= 1; dx += 2 {
		for dy := -1; dy <= 1; dy += 2 {
			// Note: feDropShadow is not supported natively by the gensvg lib.
			filter := fmt.Sprintf(
				`<feDropShadow dx="%d" dy="%d" stdDeviation="0.5" flood-color="%s" flood-opacity="%s" />`,
				dx, dy, toHex(cfg.medianLineOutlineColor), toOpacity(cfg.medianLineOutlineColor),
			)
			_, _ = canvas.Writer.Write([]byte(filter + "\n"))
		}
	}
	canvas.Fend()

	canvas.DefEnd()

	// Background
	canvas.Roundrect(
		-cfg.padding, -cfg.padding,
		width+2*cfg.padding, height+2*cfg.padding,
		cfg.bgCornerRadius, cfg.bgCornerRadius,
		toFillAttrs(cfg.bgColor),
	)

	// Merit Profiles
	localHeight := (height - totalVerticalSpacing) / (amountOfProposals)
	for proposalIndex, proposal := range proposals {
		localY := float64(proposalIndex) * (localHeight + cfg.verticalSpacing)

		// Draw the colored rectangles of the grades, and the tallies below.
		talliesNodeProperties := make([]gradeTallyNodeProperties, 0, amountOfGrades)
		localX := float64(0)
		for gradeIndex, gradeTally := range proposal.Tally {
			if gradeTally <= 0 {
				continue
			}

			gradeColor := cfg.gradesPalette[gradeIndex]
			gradeWidth := width * float64(gradeTally) / amountOfJudges

			isFirstGrade := localX == 0
			isLastGrade := math.Abs(localX+gradeWidth-width) <= 0.00001

			rectX := localX
			if !isFirstGrade {
				rectX += cfg.horizontalSpacing * 0.5
			}
			rectY := localY
			rectW := gradeWidth
			if !isFirstGrade {
				rectW -= cfg.horizontalSpacing * 0.5
			}
			if !isLastGrade {
				rectW -= cfg.horizontalSpacing * 0.5
			}
			rectH := localHeight

			// Grade color
			canvas.Roundrect(
				rectX, rectY,
				rectW, rectH,
				cfg.gradeCornerRadius, cfg.gradeCornerRadius,
				toFillAttrs(gradeColor),
			)

			// Grade pattern
			if amountOfPatterns > 0 {
				patternId := patternIds[gradeIndex%amountOfPatterns]
				canvas.Roundrect(
					rectX, rectY,
					rectW, rectH,
					cfg.gradeCornerRadius, cfg.gradeCornerRadius,
					fmt.Sprintf(`fill="url(#%s)"`, patternId),
				)
			}

			// Amounts of judgments below the grade (aka. grade tally)
			// We're going to draw them afterward, so that they end up drawn above the median line.
			// So, for now, we're only storing the values that would be wasteful to re-compute later.
			// And no, I do not want to use z-index or render-order for this, thank you very much.
			talliesNodeProperties = append(talliesNodeProperties, gradeTallyNodeProperties{
				x:     rectX + rectW*0.5,
				y:     rectY + rectH,
				tally: gradeTally,
			})

			localX += gradeWidth
		}

		// Draw the median vertical line
		canvas.Line(
			width*0.5, localY,
			width*0.5, localY+localHeight,
			fmt.Sprintf(`stroke="%s"`, toHex(cfg.medianLineColor)),
			`stroke-width="4"`,
			`stroke-dasharray="6.472 4"`,
			`filter="url(#merit_filter_blurry_outline)"`,
		)

		// Draw the name of the proposal
		nameX := 16.00 // small padding-left
		nameY := localY + 0.5*localHeight
		nameClipper := fmt.Sprintf("clipProposal%d", proposalIndex)
		canvas.Textspan(
			nameX, nameY,
			proposal.Name,
			fmt.Sprintf(
				`clip-path: url(#%s)`,
				nameClipper,
			),
			//`stroke="none"`,
			toStrokeAttrs(cfg.textColor),
			toFillAttrs(cfg.textColor),
			fmt.Sprintf(`font-size="%s"`, cfg.proposalFontSize),
			fmt.Sprintf(`font-family="%s"`, cfg.fontFamily),
			`dominant-baseline="middle"`,
			`filter="url(#merit_filter_clean_outline)"`,
		)
		canvas.Title(proposal.Name)
		canvas.TextEnd()

		// Now, after everything, draw the grade tallies
		for _, props := range talliesNodeProperties {
			canvas.Text(
				props.x, props.y,
				fmt.Sprintf("%d", props.tally),
				toFillAttrs(cfg.textColor),
				`stroke="none"`,
				fmt.Sprintf(`font-size="%s"`, cfg.tallyFontSize),
				fmt.Sprintf(`font-family="%s"`, cfg.fontFamily),
				`text-anchor="middle"`,
				`dominant-baseline="middle"`,
				`filter="url(#merit_filter_clean_outline)"`,
			)
		}
	}

	canvas.End()

	svg := stringBuilder.String()
	svg = strings.Replace(svg, vanity, "", 1)
	svg = strings.TrimSpace(svg)
	svg = strings.Replace(svg, "\n</clipPath>", "</clipPath>", -1)
	svg = strings.Replace(svg, "\n</text>", "</text>", -1)

	return svg, nil
}

type gradeTallyNodeProperties struct {
	x     float64
	y     float64
	tally uint64
}
