/*
Copyright © 2026 Sol

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package merit

import (
	"github.com/ajstarks/gensvg"
	"github.com/mieuxvoter/majority-judgment-library-go/judgment"
	"image/color"
	"strings"
)

// Proposal is also known as Candidate or Option.  It received grades from voters.
type Proposal struct {
	// Name of Proposal.  An empty string is allowed.
	Name string
	// Tally of the grades received by this Proposal, from "worst" grade to "best" grade.
	Tally []uint
}

// renderOptions uses the functional options design pattern.
// See https://uptrace.dev/blog/golang-functional-options
type renderOptions struct {
	width           float64
	height          float64
	padding         float64
	verticalSpacing float64
	cornerRadius    float64
	backgroundColor string
	gradesPalette   color.Palette
}

type RenderOptions func(options *renderOptions)

func WithWidth(width float64) RenderOptions {
	return func(options *renderOptions) {
		options.width = width
	}
}

func WithHeight(height float64) RenderOptions {
	return func(options *renderOptions) {
		options.height = height
	}
}

func WithPadding(padding float64) RenderOptions {
	return func(options *renderOptions) {
		options.padding = padding
	}
}

const vanity = "<!-- Generated by gensvg -->\n"

func RenderSvg(
	proposals []Proposal,
	opts ...RenderOptions,
) (string, error) {

	amountOfProposals := len(proposals)
	amountOfGrades := len(proposals[0].Tally)
	// FIXME: check consistency of tallies

	cfg := renderOptions{
		width:           512.00,
		height:          512.00,
		padding:         16.00,
		verticalSpacing: 16.00,
		cornerRadius:    6.00,
		backgroundColor: "#212121", // TBD: transparent, perhaps color.Color?
		gradesPalette:   judgment.CreateDefaultPalette(amountOfGrades),
	}
	for _, opt := range opts {
		opt(&cfg)
	}

	// FIXME: check consistency of grades palette

	width := cfg.width
	height := cfg.height

	stringBuilder := new(strings.Builder)
	canvas := gensvg.New(stringBuilder)
	canvas.Startview(
		width, height,
		-cfg.padding, -cfg.padding,
		width+2*cfg.padding, height+2*cfg.padding,
	)

	// Background
	//canvas.Rect(0, 0, width, height, "fill:"+cfg.backgroundColor)
	canvas.Rect(
		-cfg.padding, -cfg.padding,
		width+2*cfg.padding, height+2*cfg.padding,
		"fill:"+cfg.backgroundColor,
	)

	//canvas.Rect(0, 0, width, height, "fill:darkred")

	totalVerticalSpacing := cfg.verticalSpacing * float64(amountOfProposals-1)
	for proposalIndex, proposal := range proposals {
		localHeight := (height - totalVerticalSpacing) / float64(amountOfProposals)
		localY := float64(proposalIndex) * (localHeight + cfg.verticalSpacing)
		//canvas.Rect(0, localY, width, localHeight, "fill:magenta")

		// Draw the colored rectangles of the grades.
		localX := float64(0)
		for gradeIndex, gradeTally := range proposal.Tally {
			gradeColor := toHex(cfg.gradesPalette[gradeIndex])
			gradeWidth := width * float64(gradeTally) / 12.0
			canvas.Roundrect(
				localX, localY,
				gradeWidth, localHeight,
				cfg.cornerRadius, cfg.cornerRadius,
				"fill:"+gradeColor,
			)
			localX += gradeWidth
		}

		// Draw the median vertical line
		canvas.Line(
			width*0.5, localY,
			width*0.5, localY+localHeight,
			"stroke=\"black\"",
			"stroke-width=\"4\"",
			"stroke-dasharray=\"6.472 4\"",
		)
	}

	canvas.End()

	svg := stringBuilder.String()
	svg = strings.Replace(svg, vanity, "", 1)

	return svg, nil
}

func toHex(c color.Color) string {
	return judgment.DumpColorHexString(
		c,
		"#",
		true,
	)
}

//func renderMeritProfileSvg(canvas *gensvg.SVG, proposal Proposal, cfg renderOptions) error {
//	return nil
//}
