/*
Copyright © 2026 Sol

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package merit

import (
	"fmt"
	"github.com/ajstarks/gensvg"
	"github.com/mieuxvoter/majority-judgment-library-go/judgment"
	"image/color"
	"strings"
)

// Proposal is also known as Candidate or Option.  It received grades from voters.
type Proposal struct {
	// Name of Proposal.  An empty string is allowed.
	Name string
	// Tally of the grades received by this Proposal, from "worst" grade to "best" grade.
	Tally []uint
}

// renderOptions uses the functional options design pattern.
// See https://uptrace.dev/blog/golang-functional-options
type renderOptions struct {
	width             float64
	height            float64
	padding           float64
	verticalSpacing   float64
	gradeCornerRadius float64
	bgCornerRadius    float64
	bgColor           color.Color
	medianLineColor   color.Color
	textColor         color.Color
	outlineColor      color.Color
	gradesPalette     color.Palette
}

type RenderOptions func(options *renderOptions)

func WithWidth(width float64) RenderOptions {
	return func(options *renderOptions) {
		options.width = width
	}
}

func WithHeight(height float64) RenderOptions {
	return func(options *renderOptions) {
		options.height = height
	}
}

func WithPadding(padding float64) RenderOptions {
	return func(options *renderOptions) {
		options.padding = padding
	}
}

// const mvBlue = color.RGBA{R: 36, G: 0, B: 253, A: 255}
const vanity = "<!-- Generated by gensvg -->\n"
const xmlHeader = "<?xml version=\"1.0\"?>"

func RenderSvg(
	proposals []Proposal,
	opts ...RenderOptions,
) (string, error) {

	amountOfProposals := float64(len(proposals))
	amountOfGrades := len(proposals[0].Tally)
	// FIXME: check consistency of tallies

	cfg := renderOptions{
		width:             512.00,
		height:            -1.0, // dynamically computed if not set
		padding:           16.00,
		verticalSpacing:   16.00,
		gradeCornerRadius: 6.00,
		bgCornerRadius:    12.00,
		medianLineColor:   color.RGBA{R: 1, G: 1, B: 1, A: 255},
		textColor:         color.RGBA{R: 0, G: 0, B: 0, A: 255},
		outlineColor:      color.RGBA{R: 255, G: 255, B: 255, A: 255},
		bgColor:           color.RGBA{R: 255, G: 255, B: 255, A: 255},
		gradesPalette:     judgment.CreateDefaultPalette(amountOfGrades),
	}
	for _, opt := range opts {
		opt(&cfg)
	}

	// Compute a sensible, dynamic default height
	if cfg.height == -1.0 {
		cfg.height = amountOfProposals*42.0 + cfg.verticalSpacing*(amountOfProposals+1.0)
	}

	// FIXME: check consistency of grades palette

	width := cfg.width
	height := cfg.height
	totalVerticalSpacing := cfg.verticalSpacing * (amountOfProposals - 1)

	// All's well, let's start generating the SVG
	stringBuilder := new(strings.Builder)
	canvas := gensvg.New(stringBuilder)

	d := canvas.Decimals
	canvas.Start(
		width, height,
		fmt.Sprintf(
			`viewBox="%.*f %.*f %.*f %.*f"`,
			d, -cfg.padding,
			d, -cfg.padding,
			d, width+2*cfg.padding,
			d, height+2*cfg.padding,
		),
		`overflow="hidden"`,
	)

	// Definitions
	canvas.Def()
	// We use clipping paths, since overflow does not work properly.
	for proposalIndex := range proposals {
		localHeight := (height - totalVerticalSpacing) / (amountOfProposals)
		localY := float64(proposalIndex) * (localHeight + cfg.verticalSpacing)
		canvas.ClipPath(
			fmt.Sprintf(`id="clipProposal%d"`, proposalIndex),
		)
		canvas.Rect(0, localY, width, localHeight)
		canvas.ClipEnd()
	}
	canvas.DefEnd()

	// Background
	canvas.Roundrect(
		-cfg.padding, -cfg.padding,
		width+2*cfg.padding, height+2*cfg.padding,
		cfg.bgCornerRadius, cfg.bgCornerRadius,
		fmt.Sprintf(
			"fill:%s",
			toHex(cfg.bgColor),
		),
	)

	//canvas.Rect(0, 0, width, height, "fill:darkred")

	for proposalIndex, proposal := range proposals {
		localHeight := (height - totalVerticalSpacing) / (amountOfProposals)
		localY := float64(proposalIndex) * (localHeight + cfg.verticalSpacing)
		//canvas.Rect(0, localY, width, localHeight, "fill:magenta")

		// Draw the colored rectangles of the grades.
		localX := float64(0)
		for gradeIndex, gradeTally := range proposal.Tally {
			gradeColor := toHex(cfg.gradesPalette[gradeIndex])
			gradeWidth := width * float64(gradeTally) / 12.0
			canvas.Roundrect(
				localX, localY,
				gradeWidth, localHeight,
				cfg.gradeCornerRadius, cfg.gradeCornerRadius,
				"fill:"+gradeColor,
			)
			localX += gradeWidth
		}

		// Draw the median vertical line
		canvas.Line(
			width*0.5, localY,
			width*0.5, localY+localHeight,
			fmt.Sprintf(`stroke="%s"`, toHex(cfg.medianLineColor)),
			`stroke-width="4"`,
			`stroke-dasharray="6.472 4"`,
		)

		// Draw the name of the proposal, and its outline
		nameX := 12.00
		nameY := localY + 0.5*localHeight
		nameClipper := fmt.Sprintf("clipProposal%d", proposalIndex)
		canvas.Text(
			nameX, nameY,
			proposal.Name,
			fmt.Sprintf(
				`stroke:%s; fill:%s; clip-path: url(#%s)`,
				toHex(cfg.outlineColor),
				toHex(cfg.outlineColor),
				nameClipper,
			),
			`stroke-width="5"`,
			`font-size="1.3em"`,
			`dominant-baseline="middle"`,
		)
		canvas.Textspan(
			nameX, nameY,
			proposal.Name,
			fmt.Sprintf(
				`stroke:%s; clip-path: url(#%s)`,
				toHex(cfg.textColor),
				nameClipper,
			),
			`font-size="1.3em"`,
			`dominant-baseline="middle"`,
		)
		canvas.Title(proposal.Name)
		canvas.TextEnd()
	}

	canvas.End()

	svg := stringBuilder.String()
	svg = strings.Replace(svg, vanity, "", 1)
	svg = strings.Replace(svg, xmlHeader, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>", 1)

	return svg, nil
}

func toHex(c color.Color) string {
	return judgment.DumpColorHexString(
		c,
		"#",
		true,
	)
}
